# See https://alacritty.org/config-alacritty.html

[font]
size = 14

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[shell]
program = ".cargo/bin/nu"

[window]
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"
title = "Terminal"
