# See https://alacritty.org/config-alacritty.html

[font]
size = 14

# Enables Cmd+s to save on macOS in a terminal editor.
[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[scrolling]
history = 100000

[shell]
program = ".cargo/bin/nu"

[window]
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"
title = "Terminal"
