# See https://alacritty.org/config-alacritty.html

[font]
normal = { family = "IBM Plex Mono", style = "Light" }
size = 14

# Alt + Left: move left one word.
[[keyboard.bindings]]
mods = "Alt"
key = "Left"
chars = "\u001B[1;5D"

# Alt + Right: move right one word.
[[keyboard.bindings]]
mods = "Alt"
key = "Right"
chars = "\u001B[1;5C"

# Cmd + S on macOS: reinterpreted as Ctrl + S.
[[keyboard.bindings]]
mods = "Command"
key = "S"
chars = "\u0013"

# Ctrl + N: open new Alacritty instance.
[[keyboard.bindings]]
mods = "Control"
key = "N"
action = "SpawnNewInstance"

[scrolling]
history = 100000

[shell]
program = ".cargo/bin/nu"
args = ["--login", "--commands", "zellij"]

[window]
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"
title = "Terminal"
