# See https://alacritty.org/config-alacritty.html

[font]
normal = { family = "IBM Plex Mono", style = "Light" }
size = 14

# Cmd + right on macOS: home
[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001"

# Cmd + right on macOS: end
[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005"

# Cmd + S on macOS: reinterpreted as Ctrl + S.
[[keyboard.bindings]]
mods = "Command"
key = "S"
chars = "\u0013"

# Ctrl + N: open new Alacritty instance.
[[keyboard.bindings]]
mods = "Control"
key = "N"
action = "SpawnNewInstance"

[scrolling]
history = 100000

[terminal.shell]
program = ".cargo/bin/nu"
args = ["--login", "--commands", "zellij"]

[window]
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"
title = "Terminal"
