# A slick, minimal terminal emulator.
[[cask]]
name = "alacritty"
quarantine = false

# Current browser of choice.
[[cask]]
name = "brave-browser"

# A better git pager.
[[formula]]
name = "git-delta"

# Golang.
[[formula]]
name = "go"

# A common build dependency.
[[formula]]
name = "openssl@3"

# An app for conveniently moving and resizing windows.
[[cask]]
name = "rectangle-pro"

# Checks shell for syntax errors and POSIX-compliance.
[[formula]]
name = "shellcheck"

# Current code editor of choice.
[[cask]]
name = "visual-studio-code"
