# shellcheck shell=bash

BASHRC_PRIV="${HOME}/.bashrc.private"
LIB_SH="${HOME}/.dotfiles/shell/sh/lib.sh"
readonly BASHRC_PRIV LIB_SH

source "${LIB_SH}"

# Set the PATH as configured in Nushell.
set_path_from_nu

# Source a private bashrc if present.
if [ -f "${BASHRC_PRIV}" ]; then
    source "${BASHRC_PRIV}"
fi

