NU="${HOME}/.cargo/bin/nu"
BASHRC_PRIV="${HOME}/.bashrc.private"
readonly NU BASHRC_PRIV

# Set the PATH as configured in Nushell.
if [ -f "${NU}" ]; then
    PATH="$("${NU}" --login --commands "do \$env.ENV_CONVERSIONS.PATH.to_string \$env.PATH")"
    export PATH
fi

# Source a private bashrc if present.
if [ -f "${BASHRC_PRIV}" ]; then
    source "${BASHRC_PRIV}"
fi

