NU="${HOME}/.cargo/bin/nu"
ZSHRC_PRIV="${HOME}/.zshrc.private"
readonly NU ZSHRC_PRIV

# Set the PATH as configured in Nushell.
if [ -f "${NU}" ]; then
    PATH="$("${NU}" --login --commands "do \$env.ENV_CONVERSIONS.PATH.to_string \$env.PATH")"
    export PATH
fi

# Source a private zshrc if present.
if [ -f "${ZSHRC_PRIV}" ]; then
    source "${ZSHRC_PRIV}"
fi

