LIB_SH="${HOME}/.dotfiles/shell/sh/lib.sh"
ZSHRC_PRIV="${HOME}/.zshrc.private"
readonly LIB_SH ZSHRC_PRIV

source "${LIB_SH}"

# Set the PATH as configured in Nushell.
set_path_from_nu

# Source a private zshrc if present.
if [ -f "${ZSHRC_PRIV}" ]; then
    source "${ZSHRC_PRIV}"
fi

