#!/bin/sh

# A wrapper script for invoking make commands with `compiledb` to automatically
# generate compile_commands.json.

# compiledb expects the supplied command to start with just "make". To satisfy
# this and to avoid this script being re-entrant, we prefix $PATH with the next
# highest precedent `make`. 
next_make="$(nu -c "which -a make | get path.1")"
PATH="$(dirname "${next_make}"):$PATH"

compiledb make "${@}"
